### PR TITLE
Update topnav_ioos.yml

### PR DESCRIPTION
**Pull request by MathewBiddle**
data demo center is now IOOS CodeLab

### CODE REVIEW

**Comment by mwengren** [comment]
Hey @MathewBiddle I started working on a bigger overhaul of the topnav bar, including this change to the CodeLab name.  Basically what was discussed here: https://github.com/ioos/documentation-theme-jekyll/issues/10.  

If you don't mind, lets hold off on making this change and I'll try to put a PR up next week.

**Comment by MathewBiddle** [comment]
Sounds good @mwengren.

**Comment by mwengren** [comment]
See #12 as a replacement for this

**Comment by mwengren** [comment]
Closing this out to clean up, superseded by #12

**Pull request closed without merging**
