### PR TITLE
update site for the glider dac

### PR DESCRIPTION
**Pull request by ocefpaf**
Should we use `IOOS National Glider DAC` for the title here? See https://github.com/ioos/ioos.github.io/pull/8.

### CODE REVIEW

**Comment by mwengren** [comment]
@ocefpaf @MathewBiddle @kbailey-noaa 

I was trying to remember where I had brainstormed options for making the various file format documentation sites we have seem more consistent, and I remembered!  It's not in a public location, but you all can see [here](https://docs.google.com/document/d/1mMm3xN1hes5ZdgVaxRAtf4nUmRo6IDL0JLXT7b-jpoY/edit#heading=h.gfpcgwszsli2) (scroll to the bottom of the 7/13 meeting notes).

Here's a version of the same comments for public discussion (sorry to sidetrack your PR Filipe...):

**Issue**: inconsistency in the various Data & File Format pulldown menu links.  If you look at the Data Standards & Formats menu at [ioos.github.io](http://ioos.github.io/), currently, we have: 
* IOOS Metadata Profile, 
* IOOS Glider DAC Data Format & Guidelines, 
* IOOS ATN Specification,  
* MBON Data File & Formatting 
and more...

It's not clear that these are comparable links to sites about file formatting (and sometimes other info as well in the case of the Glider DAC and MBON, I believe).

**Suggestion**: We could rename options for some of the Data Standards & Formats menu options, perhaps settle on 'Specification' across the board?  I’d prefer to keep IOOS Metadata Profile named as is (hoping someday to have the others inherit from it):
* IOOS Metadata Profile
* IOOS Glider Specification
* IOOS ATN Specification
* MBON Data Specification

Another option would be breaking out the Glider DAC documentation into two menu links: one that goes directly to the Glider DAC 'Data Format' page (https://ioos.github.io/glider-dac/ngdac-netcdf-file-format-version-2.html) from the Data Standards & Formats menu link above and another in a different menu category perhaps that goes to the File Submission Process page (https://ioos.github.io/ioosngdac/ngdac-netcdf-file-submission-process.html) page, or elsewhere if the site is redesigned as part of the migration or if you think another landing page would be better.  

I think I'd prefer the simpler approach and just rename the various formats to 'Specification' for now if we're on board with that, but maybe it's worth reconsidering the pulldown menu categories/names instead if this is confusing or not preferred (i.e. using 'IOOS Glider Specification' rather than 'IOOS National Glider DAC' for example, or not being clear that that site contains more info than just file formatting guidelines/requirements).

I came up with these categories as a first attempt when @MathewBiddle and I were redoing the menu earlier this year, but there's probably room for improvement.  

What do you think?

**Comment by ocefpaf** [comment]
> I think I'd prefer the simpler approach and just rename the various formats to 'Specification' for now if we're on board with that

@mwengren I believe this was the outcome of the meeting right? I can implement that in this PR.

**Comment by MathewBiddle** [comment]
works for me 😄

**Comment by mwengren** [comment]
Looks good, thanks!

**Pull request merged**
