### PR TITLE
Update topnav per: ioos/documentation-theme-jekyll/issues/10

### PR DESCRIPTION
**Pull request by mwengren**
xref: ioos/documentation-theme-jekyll#10

See rendered version of proposed topnav layout here: https://mwengren.github.io/ioos-documentation-jekyll-skeleton/howto.html

@MathewBiddle what do you think?  

Workflow to create this PR and render the forked mwengren/ioos-documentation-jekyll-skeleton GH Pages site above (for my own future reference):
* create new micah_dev branch in _data/navbars submodule on ioos/ioos-documentation-jekyll-skeleton (`checkout -b micah_dev`)
* make changes & preview locally in jekyll
* push micah_dev branch to ioos/documentation-theme-jekyll (otherwise GH Pages build step will fail because the commit hash is not able to be found/checked out by GHA in the repo - see: https://github.com/mwengren/ioos-documentation-jekyll-skeleton/actions/runs/4639155396)
* in ioos/ioos-documentation-jekyll-skeleton root (outside of submodule), commit on gh-pages branch with _data/navbar submodule micah_dev branch update, push gh-pages branch to mwengren/ioos-documentation-jekyll-skeleton to render gh-pages site for preview
* create this PR on GitHub using previously pushed micah_dev branch
* once PR is merged, delete my local ioos/ioos-documentation-jekyll-skeleton gh-pages branch and replace with upstream because the GHA 'sync_theme_submodules' job will duplicate the _data/navbars submodule update commit caused by this PR merge.  Note: to reset submodules on gh-pages branch to default instead of micah_dev,  using `--remote` flag may be needed: `git submodule update --remote` - but this is moot since branch will ultimately be deleted/replaced
* repeat the above again in the future only if absolutely necessary...

### CODE REVIEW

**Review by MathewBiddle — APPROVED** [review]
This looks great!

I really like the use of `external_url` here.

**Comment by mwengren** [comment]
Thanks.  Although it wouldn't be the end of the world if the topnav bar disappeared from these sites briefly, maybe we should merge it early next week (or on Sunday if one of us remembers) in case something goes amiss with the GHA daily updates.

Rather than making a PR, I did make a straight [commit](https://github.com/ioos/documentation-theme-jekyll/commit/e51d3d836fea1960bae3b9c9c783e3782d4f3625) of a change to the main branch to fix one of the includes, that should be pulled by the next GHA run, but I don't think it will break anything.

**Comment by MathewBiddle** [comment]
Something broke:
image

**Comment by MathewBiddle** [comment]
I was following the link in the description of this repo. That link should point to https://ioos.github.io/ioos-documentation-jekyll-skeleton/howto.html (which is functioning).

I like the cleaned up separators. Okay to merge when ready.

**Comment by mwengren** [comment]
Yeah, we deleted the GH Pages site for this repository itself when we were editing a few months ago so now it's a 404.  

I'll just update the repo link to the HOWTO page instead, we missed that step.  

I'll go ahead and merge this now, thanks!

Looks like GHA pulled in my theme submodule update as expected already at least for the skeleton repo: https://github.com/ioos/ioos-documentation-jekyll-skeleton/commits/gh-pages.  Tomorrow the topnavs should all be updated :crossed_fingers:

**Pull request merged**
